server:
  port: 8888
  servlet:
    context-path: /spark-visual
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: utf-8
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  datasource:
    mysql:
      jdbcUrl: jdbc:mysql://172.16.75.137:3390/icourt?useUnicode=true&characterEncoding=utf-8
      username: admin
      password: admin@123
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
        connection-timeout: 20000
#        connection-test-query: select 1
#    clickhouse:
#      jdbcUrl: jdbc:clickhouse://localhost:8123/ods
#      username: default
#      password: 123123
#      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#      hikari:
#        maximum-pool-size: 10
#        minimum-idle: 1
#        idle-timeout: 300000
#        connection-timeout: 20000
#        connection-test-query: select 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
